
INSERT INTO BOARD(TITLE, CONTENT, WRITER, PASSWORD) VALUES( '오이쉬에', '밥은 줍니까', '원이', '$2b$12$yH7GLIjKA7avGOgqvkw6luYDVsrojn1UAYGLpTUMaWcs7pMfUoRwu');
INSERT INTO BOARD(TITLE, CONTENT, WRITER, PASSWORD) VALUES( '파라파라나 춰야지', '오이데 오이데', '미나미', '$2b$12$dy3REkbXFAdkC9utz8V9JO0glaTFng5H2QeM4Q6oi/MeuIHrPiUVi');
INSERT INTO BOARD(TITLE, CONTENT, WRITER, PASSWORD) VALUES( '신라공주', '내는 원래 고윤정 배우님을 사랑해', '제나', '$2b$12$ON1AHgwQ6dJLC1IQPbs9Y.WCASchlERXUwdIF9ao3YbDOvTY1SSyC');